apiVersion: v1
kind: Service
metadata:
  name: devpulse-demo-java-shop
  labels:
    app: devpulse-demo-java-shop
spec:
  type: ClusterIP
  selector:
    app: devpulse-demo-java-shop
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
